version: "3.9"
services:
 java1:
  image: openjdk:19
  container_name: java_1
  ports:
   - "8080:8080"
  command: ["bin/bash"]
  volumes:
   - ./:/code
  stdin_open: true
  tty: true
 java2:
  image: openjdk:19
  container_name: java_2
  ports:
   - "8081:8080"
  command: ["bin/bash"]
  volumes:
   - ./:/code
  stdin_open: true
  tty: true
 java3:
  image: openjdk:19
  container_name: java_3
  ports:
   - "8082:8080"
  command: ["bin/bash"]
  volumes:
   - ./:/code
  stdin_open: true
  tty: true
